### ISSUE TITLE
java.net.SocketTimeoutException: SSL handshake timed out

### ISSUE THREAD

**Issue by hendy79** [alexeyvasilyev/rtsp-client-android#41]
Getting error when trying to start rtsp stream
`
sslSocket = NetUtils.createSslSocketAndConnect(rtspUri.host!!, rtspUri.port, 10000)
rtspClient = RtspClient.Builder(sslSocket!!, rtspUri.toString(), stopped, rtspClientListener)
  .requestVideo(true)
  .requestAudio(true)
  .withDebug(false)
  .withUserAgent("RTSP client")
  .withCredentials(rtspCred, rtspCred)
  .build()
rtspClient?.execute() //this line produce error
`
Here is the error
`
java.net.SocketTimeoutException: SSL handshake timed out
2022-03-07 12:34:34.305 15056-15134/com.irumatech.camerabtsdetector W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2022-03-07 12:34:34.305 15056-15134/com.irumatech.camerabtsdetector W/System.err:     at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
2022-03-07 12:34:34.305 15056-15134/com.irumatech.camerabtsdetector W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
2022-03-07 12:34:34.305 15056-15134/com.irumatech.camerabtsdetector W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.waitForHandshake(ConscryptFileDescriptorSocket.java:473)
2022-03-07 12:34:34.306 15056-15134/com.irumatech.camerabtsdetector W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.getInputStream(ConscryptFileDescriptorSocket.java:436)
2022-03-07 12:34:34.306 15056-15134/com.irumatech.camerabtsdetector W/System.err:     at com.alexvas.rtsp.RtspClient.execute(RtspClient.java:249)
2022-03-07 12:34:34.306 15056-15134/com.irumatech.camerabtsdetector W/System.err:     at com.irumatech.camerabtsdetector.MainActivity$onCreate$2$1.invokeSuspend(MainActivity.kt:217)
`
I already using this library for surfaceview and want to record the stream using rtspclient but producing error like that

**Comment by sarimmehdi** [comment]
hey @hendy79, did you manage to find a solution to this? I am also trying to record via this library but no luck so far
