### ISSUE TITLE
Always return "Read time out" error message. 

### ISSUE THREAD

**Issue by mintheinwin** [alexeyvasilyev/rtsp-client-android#69]

**Comment by Praveen-Sundriyal** [comment]
Handshake failed 
i don't get it 
is there anything i miss 


opservice is null false
2024-01-12 18:37:26.080 31159-32381 System.err              com.alexvas.rtsp.demo                W  javax.net.ssl.SSLHandshakeException: Handshake failed
2024-01-12 18:37:26.080 31159-32381 System.err              com.alexvas.rtsp.demo                W  	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:288)
2024-01-12 18:37:26.080 31159-32381 System.err              com.alexvas.rtsp.demo                W  	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.waitForHandshake(ConscryptFileDescriptorSocket.java:476)
2024-01-12 18:37:26.080 31159-32381 System.err              com.alexvas.rtsp.demo                W  	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.getInputStream(ConscryptFileDescriptorSocket.java:439)
2024-01-12 18:37:26.080 31159-32381 System.err              com.alexvas.rtsp.demo                W  	at com.alexvas.rtsp.RtspClient.execute(RtspClient.java:259)
2024-01-12 18:37:26.080 31159-32381 System.err              com.alexvas.rtsp.demo                W  	at com.alexvas.rtsp.widget.RtspSurfaceView$RtspThread.run(RtspSurfaceView.kt:277)
2024-01-12 18:37:26.081 31159-32381 System.err              com.alexvas.rtsp.demo                W  Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7300ed3788: Failure in SSL library, usually a protocol error
2024-01-12 18:37:26.081 31159-32381 System.err              com.alexvas.rtsp.demo                W  error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/tls_record.cc:242 0x72f3b39e6b:0x00000000)
2024-01-12 18:37:26.081 31159-32381 System.err              com.alexvas.rtsp.demo                W  	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2024-01-12 18:37:26.081 31159-32381 System.err              com.alexvas.rtsp.demo                W  	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
2024-01-12 18:37:26.081 31159-32381 System.err              com.alexvas.rtsp.demo                W  	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
2024-01-12 18:37:26.081 31159-32381 System.err              com.alexvas.rtsp.demo                W  	... 4 more

**Comment by maisak3** [comment]
same thing for me
