### ISSUE TITLE
The sound I heard was not correct

### ISSUE THREAD

**Issue by chimsedb** [alexeyvasilyev/rtsp-client-android#7]
I can only hear a rustling sound when I speak into my microphone from the source
- My sdpInfo from onRtspConnected : 
2021-03-16 02:03:04.674 29627-29672/com.alexvas.rtsp.demo D/RtspClient.SdpInfo: {"audioTrack":{"audioCodec":0,"channels":2,"mode":"AAC-hbr","sampleRateHz":44100,"payloadType":96,"request":"/trackID\u003d1"},"sessionName":"205"}

Please help me @@

**Comment by alexeyvasilyev** [comment]
What exact camera model do you have?

**Comment by chimsedb** [comment]
i am using google pixel 3 XL . Can u support that ?

**Comment by alexeyvasilyev** [comment]
I mean to what RTSP source are you trying to connect to?

**Comment by chimsedb** [comment]
https://github.com/begeekmyfriend/yasea
I am using this for broacast

**Comment by alexeyvasilyev** [comment]
Used to work. Now I'm getting 404 error.

**Comment by chimsedb** [comment]
Sorry my server die . Can u try again ?

**Comment by alexeyvasilyev** [comment]
It works now.
What I see at the moment that audio decoder is constantly crashing.

```
m=audio 0 RTP/AVP 96
a=rtpmap:96 mpeg4-generic/44100/2
a=fmtp:96 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1210fff15081ffdffc
a=control:trackID=1


Audio: AAC LC, sample rate: 44100 Hz, channels: 2


AudioDecodeThread: Decoder format changed: {aac-drc-heavy-compression=1, sample-rate=44100, aac-drc-boost-level=127, aac-drc-output-loudness=-1, mime=audio/raw, channel-count=2, aac-drc-effect-type=3, aac-drc-cut-level=127, aac-encoded-target-level=-1, aac-max-output-channel_count=8, aac-target-ref-level=64, aac-drc-album-mode=0}


    Process: com.alexvas.rtsp.demo, PID: 15669
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
        at com.alexvas.rtsp.demo.decode.AudioDecodeThread.run(AudioDecodeThread.kt:81)
```

ffmpeg shows 
```
Audio: aac (LC), 44100 Hz, stereo, fltp
```

I have not tested on stereo audio sources. Can you switch to mono and check if the problem still exists?

**Comment by chimsedb** [comment]
change AudioFormat.CHANNEL_IN_MONO to AudioFormat.CHANNEL_IN_MONO from my broadcast right?

**Comment by alexeyvasilyev** [comment]
No. Enable wowza send mono audio only.

**Comment by chimsedb** [comment]
ok i will try

**Comment by alexeyvasilyev** [comment]
Another option to try in AudioDecodeThread.kt
```
//        val csd0 = getAacDecoderConfigData(sampleRate, channelCount)
//        val bb = ByteBuffer.wrap(csd0)
//        format.setByteBuffer("csd-0", bb)
        format.setInteger(MediaFormat.KEY_CHANNEL_COUNT, channelCount)
        format.setInteger(MediaFormat.KEY_SAMPLE_RATE, sampleRate)
        format.setInteger(MediaFormat.KEY_AAC_PROFILE, MediaCodecInfo.CodecProfileLevel.AACObjectLC)
```
And change there every AudioFormat.CHANNEL_OUT_MONO to AudioFormat.CHANNEL_OUT_STEREO

**Comment by chimsedb** [comment]
Ok i will test latter then confirm for u . Thank u so much !!

**Comment by alexeyvasilyev** [comment]
I made small changes to 1.3.1. It will not fix your problem. But at least it is not crashing at the moment.

**Comment by chimsedb** [comment]
I think this issue from me 
When i change CHANNEL_IN_STEREO -> CHANNEL_IN_MONO from broadcast i can hear my voice but speed of my voice x2 or x3 and have loss ( I think my protocol is UDP) and my Buffer Size has config to fit with CHANNEL_IN_STEREO (I think so)
![image](https://user-images.githubusercontent.com/47516091/111320784-e977e880-8699-11eb-8c91-013dffce05b6.png)
and here is my config 
![image](https://user-images.githubusercontent.com/47516091/111321464-876bb300-869a-11eb-9916-ac246ac32e44.png)
I was use vlc lib and exoplayer to load rtsp url but all delay and cant not support low latency when i use your lib video loading good for me but i cant here my sound . 
Do you have any suggestions for me about livestreaming video ( I cant use web rtc bc this project i maintenance cant change) ?
I don't have much experience with it
