### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=228; index=228

### ISSUE THREAD

**Issue by hujinhuahjh** [alexeyvasilyev/rtsp-client-android#99]
When I use this library to play an RTSP stream, it always throws an error:
    java.lang.ArrayIndexOutOfBoundsException: length=228; index=228
at com.alexvas.utils.VideoCodecUtils.isAnyKeyFrame(VideoCodecUtils.kt:307)
at com.alexvas.rtsp.widget.RtspProcessor$proxyClientListener$1.onRtspVideoNalUnitReceived(RtspProcessor.kt:210)
at com.alexvas.rtsp.RtspClient.readRtpData(RtspClient.java:735)
at com.alexvas.rtsp.RtspClient.execute(RtspClient.java:542)
at com.alexvas.rtsp.widget.RtspProcessor$RtspThread.run(RtspProcessor.kt:348)

I am using your demo and have tried both software decoding, hardware decoding, and other Android devices; all of them result in errors.

I modify the code in VideoCodeUtils.kt (in 308):  val nalUnitTypeOctet = data[nalUnitOffset]
to
val nalUnitTypeOctet = try {
                    data[nalUnitOffset]
                } catch (e: ArrayIndexOutOfBoundsException) {
                    return false
                }
it works well

**Comment by alexeyvasilyev** [comment]
Thanks for letting me know. try/catch is not the best way for fixing it since it creates overhead. I fixed slightly differently.
